### PR TITLE
EDA Done by Leanne

### PR DESCRIPTION
**Pull request by Joyfreaky**
The EDA has been checked and the file runs correctly, need to resolve some conflicts with other files.

### CODE REVIEW

**Comment by Joyfreaky** [comment]
Do not merge, needs to resolve conflict, once conflict it resolved, review and merge

**Comment by Joyfreaky** [comment]
All the conflicts have been resolved and the code look good to me.

**Review by Leannechen0420 — APPROVED** [review]
This looks good, everything is fine, we can discuss more changes after the test data analysis.

**Comment by Joyfreaky** [comment]
I have turned off the signed commit for now, because configuration was not in place to check signed commits

**Pull request merged**
